name: 3d-unet-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - absl-py=2.1.0
  - anyio=4.2.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - conda=24.5.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - idna=3.7
  - imageio=2.34.0
  - importlib-metadata=7.0.1
  - importlib-resources=6.4.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - json5=0.9.6
  - jsonschema=4.19.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_server=2.10.0
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.43
  - libsodium=1.0.18
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - packaging=24.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=23.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - python=3.9.19
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - requests=2.31.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - terminado=0.17.1
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.7.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2023c
  - ujson=5.8.0
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.41.2
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
